#!/usr/bin/env python
import logging
import signal
import lib.logger as log
import lib.parser as prsr
import lib.constants as cte
from lib.udp_client import UDPClient


def main():
    parser = prsr.download()
    args = parser.parse_args()
    
    log.configure_log(args.verbosity, cte.UPLOAD_CLIENT_LOG_FILE)
    logger = logging.getLogger(__name__)
    logger.debug(f'Arguments: {args}')

    cli = UDPClient(args.host, args.port, args.dst, args.name, False)

    try:
        cli.start()
        cli.run()
    except SignalException:
        logger.info("Exiting client...")
    except Exception:
        logger.critical('Unknown Error - Client closed')
    finally:
        logger.info("Stopping client...")
        cli.stop()


class SignalException(Exception):
    # do nothing
    pass


def handler(signum, frame):
    raise SignalException()


if __name__ == "__main__":
    signal.signal(signal.SIGINT, handler)
    signal.signal(signal.SIGTERM, handler)
    main()
